// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SchedulerSettings.Models
{
    public enum ToastScenarioIntern
    {
        // Summary:
        //     The normal Toast behavior. The Toast appears for a short duration, and then automatically
        //     dismisses into Action Center.
        Default = 0,
        // Summary:
        //     Causes the Toast to stay on-screen and expanded until the user takes action.
        //     Also causes a looping alarm sound to be selected by default.
        Alarm = 1,
        // Summary:
        //     Causes the Toast to stay on-screen and expanded until the user takes action.
        Reminder = 2,
        // Summary:
        //     Causes the Toast to stay on-screen and expanded until the user takes action (on
        //     Mobile this expands to full screen). Also causes a looping incoming call sound
        //     to be selected by default.
        IncomingCall = 3,
    }
}
